Update termux

diff --git a/termux b/termux
--- a/termux
+++ b/termux
@@ -1,28 +1,46 @@
 #!/bin/bash
 
+download() {
+	url="$1"
+	output="$2"
+	file=`basename $url`
+	if [[ -e "$file" || -e "$output" ]]; then
+		rm -rf "$file" "$output"
+	fi
+	curl --silent --insecure --fail --retry-connrefused \
+		--retry 3 --retry-delay 2 --location --output "${file}" "${url}"
 
-function setup_ngrok() {
-echo -e $" \e[91m[\e[0m-\e[91m]\e[1;92m Download Ngrok...\e[0m  "
-	if [ ! -f  "${BIN}/ngrok" ]; then
-             if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
-		     ngrok_url="https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm.zip"
-             elif [[ "$arch" == *'aarch64'* ]]; then
-                     ngrok_url="https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.zip"
-             elif [[ "$arch" == *'x86_64'* ]]; then
-                    if [[ "$ArNam" == *'amd64'* ]]; then
-                                ngrok_url="https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip"
-                    else
-                                ngrok_url="https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.zip"
-                    fi
-             else
-                                ngrok_url="https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-386.zip"
-             fi
-	     		launch="installing server-2, size@4mb";splashdown="Installed.";echo
-		(wget --quiet ${ngrok_url}  )&
-	     unzip -q ngrok*.zip && chmod +x ngrok
-	     	          
-        else 
-	    echo ""
+	if [[ -e "$file" ]]; then
+		if [[ ${file#*.} == "zip" ]]; then
+			unzip -qq $file > /dev/null 2>&1
+		elif [[ ${file#*.} == "tgz" ]]; then
+			tar -zxf $file > /dev/null 2>&1
+		else
+		fi
+		chmod +x $output > /dev/null 2>&1
+		rm -rf "$file"
+	else
+		echo -e "\n${RED}[${WHITE}!${RED}]${RED} Error occured while downloading ${output}."
+		{ reset_color; exit 1; }
+	fi
+}
+
+## Install ngrok
+install_ngrok() {
+	if [[ -e "ngrok" ]]; then
+		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${GREEN} Ngrok already installed."
+	else
+		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing ngrok..."${WHITE}
+		arch=`uname -m`
+		if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
+			download 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm.tgz' 'ngrok'
+		elif [[ "$arch" == *'aarch64'* ]]; then
+			download 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.tgz' 'ngrok'
+		elif [[ "$arch" == *'x86_64'* ]]; then
+			download 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz' 'ngrok'
+		else
+			download 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-386.tgz' 'ngrok'
+		fi
 	fi
 }
 		
@@ -30,59 +48,62 @@ echo -e $" \e[91m[\e[0m-\e[91m]\e[1;92m Download Ngrok...\e[0m  "
 
 
 
-function setup_cloudflare() {
-echo -e $" \e[91m[\e[0m-\e[91m]\e[1;92m Download Cloudflared...\e[0m  "
-	if [ ! -f ${BIN}/cloudflared ]; then
-             if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
-		     cloudd="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm"
-             elif [[ "$arch" == *'aarch64'* ]]; then
-                     cloudd="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64"
-             elif [[ "$arch" == *'x86_64'* ]]; then
-                    if [[ "$ArNam" == *'amd64'* ]]; then
-                                cloudd="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
-                    else
-                                cloudd="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64"
-                    fi
-             else
-                                cloudd="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-386"
-             fi
-	          launch="Installing server-1, size@25mb";splashdown="installed.";echo
-	          (wget --quiet ${cloudd} )& 
-		    chmod +x cloudflared* && mv cloudflare* cloudflared      
-        else 
-	    echo ""
+## Install Cloudflared
+install_cloudflared() {
+	if [[ -e "cloudflared" ]]; then
+		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${GREEN} Cloudflared already installed."
+	else
+		echo -e "\n${GREEN}[${WHITE}+${GREEN}]${CYAN} Installing Cloudflared..."${WHITE}
+		arch=`uname -m`
+		if [[ ("$arch" == *'arm'*) || ("$arch" == *'Android'*) ]]; then
+			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm' 'cloudflared'
+		elif [[ "$arch" == *'aarch64'* ]]; then
+			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64' 'cloudflared'
+		elif [[ "$arch" == *'x86_64'* ]]; then
+			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64' 'cloudflared'
+		else
+			download 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-386' 'cloudflared'
+		fi
 	fi
 }
 
 
-link_server() {
-echo -e $" \e[91m[\e[0m-\e[91m]\e[1;92m Launching Cloudflared...\e[0m  "
-rm -rf cld.log
-			   echo -ne "  "
-   		           if [[ `command -v termux-chroot` ]]; then
-			  sleep 2 && termux-chroot cloudflared* tunnel -url 127.0.0.1:4444 --logfile cld.log > /dev/null 2>&1 &
-   			  else
-     		           sleep 2 && ./cloudflared* tunnel -url 127.0.0.1:4444 --logfile cld.log > /dev/null 2>&1 &
-   	                 fi
-			{ sleep 8; clear; }
-				clink=$(grep -o 'https://[-0-9a-z]*\.trycloudflare.com' "cld.log")
-			   echo ""
-		 }	   
+start_cloudflared() { 
+	rm cld.log > /dev/null 2>&1 &
+	echo -e "\n${RED}[${WHITE}-${RED}]${GREEN} Initializing... ${GREEN}( ${CYAN}http://$HOST:$PORT ${GREEN})"
+	{ sleep 1; }
+	echo -ne "\n\n${RED}[${WHITE}-${RED}]${GREEN} Launching Cloudflared..."
+
+	if [[ `command -v termux-chroot` ]]; then
+		sleep 2 && termux-chroot ./.server/cloudflared tunnel -url "127.0.0.1":"4444" --logfile cld.log > /dev/null 2>&1 &
+	else
+		sleep 2 && ./.server/cloudflared tunnel -url "127.0.0.1":"4444" --logfile cld.log > /dev/null 2>&1 &
+	fi
+
+	sleep 8
+	cldflr_url=$(grep -o 'https://[-0-9a-z]*\.trycloudflare.com' "cld.log")
+	custom_url "$cldflr_url"
+	capture_data
+}	   
 
 
-link_server2() {
-            echo ""       echo -e $" \e[91m[\e[0m-\e[91m]\e[1;92m Launching Ngrok...\e[0m  "
-	    unzip ngrok*.zip
-			   echo -e $" \e[91m[\e[0m Online HacKing\e[91m]\e[1;92m Wait For Start.....\e[0m  "
-			   echo -ne ""
-                           if [[ `command -v termux-chroot` ]]; then
-                           sleep 1 && termux-chroot ./ngrok http 127.0.0.1:4444 > /dev/null 2>&1 & 
-                          else
-                            sleep 1 && ./ngrok http 127.0.0.1:4444 > /dev/null 2>&1 &
-                         fi
-	                 { sleep 8; clear; }
-	                       nlink=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[-0-9a-z]*\.ngrok.io")
-			       echo ""
+start_ngrok() {
+	echo -e "\n${RED}[${WHITE}-${RED}]${GREEN} Initializing... ${GREEN}( ${CYAN}http://127.0.0.1:4444 ${GREEN})"
+	{ sleep 1; }
+	echo -e "\n"
+	read -n1 -p "${RED}[${WHITE}-${RED}]${ORANGE} Change Ngrok Server Region? ${GREEN}[${CYAN}y${GREEN}/${CYAN}N${GREEN}]:${ORANGE} " opinion
+	[[ ${opinion,,} == "y" ]] && ngrok_region="eu" || ngrok_region="us"
+	echo -e "\n\n${RED}[${WHITE}-${RED}]${GREEN} Launching Ngrok..."
+
+	if [[ `command -v termux-chroot` ]]; then
+		sleep 2 && termux-chroot ./.server/ngrok http --region ${ngrok_region} "127.0.0.1":"4444" --log=stdout > /dev/null 2>&1 &
+	else
+		sleep 2 && ./.server/ngrok http --region ${ngrok_region} "127.0.0.1":"4444" --log=stdout > /dev/null 2>&1 &
+	fi
+
+	sleep 8
+	ngrok_url=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -Eo '(https)://[^/"]+(.ngrok.io)')
+
 }
 
 
@@ -93,10 +114,10 @@ links() {
 			   echo ""
 			   echo -e " "
                            echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > >\e[0m'
-                           printf "\e[1;33m\e[0m\e[1;33m Cloudflared Link :\e[0m\e[1;77m %s\e[0m\n" $clink                                   
+                           printf "\e[1;33m\e[0m\e[1;33m Cloudflared Link :\e[0m\e[1;77m %s\e[0m\n" $cldflr_url                                 
                            echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
                            echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > >\e[0m'
-                           printf "\e[1;33m\e[0m\e[1;33m Modify Link :\e[0m\e[1;77m %s\e[0m\n" $nlink
+                           printf "\e[1;33m\e[0m\e[1;33m Modify Link :\e[0m\e[1;77m %s\e[0m\n" $ngrok_url
                            echo -e $'\e[1;33m\e[0m\e[1;77m\e[0m\e[1;33m\e[0m\e[1;96m ------------------------- > > > > > > >\e[0m'
 			   echo ""
 			   echo ""
@@ -106,10 +127,8 @@ links() {
 
 
 chmod +x *
-setup_ngrok
-unzip ngrok*.zip
-setup_cloudflare
-mv cloudflare* cloudflared
-link_server
-link_server2
+install_ngrok
+install_cloudflared
+start_cloudflared
+start_ngrok
 links
